version: '3.3'
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=Start123.
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    image: snickch/flask001:v2
    container_name: flask
    restart: always
    expose:
        - 5000
    volumes:
      - ./app:/app
      - ./app/static/img/books:/app/static/img/books:rw
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - "db"